@php
    $home = url('/');
    $description = __('Open source URL shortener: short links on your own domain, cookieless click metrics, privacy by design, self-hostable.');
    // Blade compiles `@context` as a directive (Laravel 11 added one), so the
    // sigil is kept out of the template text — otherwise this array ships as
    // compiled PHP instead of JSON.
    $at = '@';
    $jsonLd = [
        $at.'context' => 'https://schema.org',
        $at.'type' => 'SoftwareApplication',
        'name' => config('app.name'),
        'applicationCategory' => 'DeveloperApplication',
        'operatingSystem' => 'Web',
        'url' => $home,
        'description' => $description,
        'offers' => [$at.'type' => 'Offer', 'price' => '0', 'priceCurrency' => 'USD'],
        'license' => 'https://opensource.org/licenses/MIT',
    ];
    $shortHost = config('nexo.short_host');
    $canRegister = config('nexo.auth_mode') !== 'sso' && config('nexo.allow_registration');
    // One verb, one destination: wherever this instance lets a person start.
    // With registration closed there is no second button — a ghost "Sign in"
    // pointing at the same page as the primary is just the CTA said twice.
    $start = $canRegister ? route('register') : route('login');

    // The product in the order a person meets it. Every figure is a real
    // capture of this app (public/landing, regenerated by nexo-shots.mjs from a
    // local instance seeded with DemoSeeder) — never a redrawn screen.
    $steps = [
        ['shot' => 'shot-1', 'caption' => __('1 — Paste the long URL')],
        ['shot' => 'shot-2', 'caption' => __('2 — Share the short link')],
        ['shot' => 'shot-3', 'caption' => __('3 — Read your numbers, cookie-free')],
    ];

    // Every row is something the code enforces, and the source is named next to
    // it. A row with no real source does not exist (design.md, "Copy").
    $specs = [
        // config/nexo.php → slug.min_length / slug.max_length, App\Support\SlugGenerator.
        [__('Automatic slug'), __('base62, :min–:max characters', [
            'min' => config('nexo.slug.min_length'),
            'max' => config('nexo.slug.max_length'),
        ])],
        // App\Rules\ReservedSlug::FORMAT.
        [__('Custom slug'), __('3–32 characters (letters, numbers, - and _)')],
        // App\Http\Controllers\RedirectController (302, never permanent) + the
        // no-store header from the short host's middleware.
        [__('Redirect'), __('302, no caching')],
        // App\Support\VisitorHash (ADR-006).
        [__('Metrics'), __('Irreversible daily hash — no IP or cookie stored')],
        // config/nexo.php → locales, plus the shared theme toggle.
        [__('Languages and themes'), __('es · en · pt — light and dark')],
    ];

    // The same answers the help center gives, in the same words — the landing
    // does not get a marketing rewrite of them.
    $faqs = array_slice((array) __('help.faqs'), 0, 4);
@endphp

{{-- The head is the shared x-nexo-seo component (via panel-layout → partials/head);
     only the structured data is page-specific — the landing describes the software
     itself, not a generic WebSite. --}}
<x-panel-layout :title="__('Shorten links with cookieless metrics.')" :description="$description" :seo-json-ld="$jsonLd">
    {{-- Only the hero carries a primary CTA (design.md, "CTA voice"): the
         header's account action used to be a second solid violet button with a
         different verb, competing with it a few pixels away. Signing up lives
         in the hero, where the claim it answers is. --}}
    <x-slot:actions>
        @auth
            <a href="{{ route('panel') }}" class="nexo-btn nexo-btn--ghost">{{ __('Your links') }}</a>
        @else
            <a href="{{ route('login') }}" class="nexo-btn nexo-btn--ghost">{{ __('Sign in') }}</a>
        @endauth
    </x-slot:actions>

    <section data-landing-section="hero">
        <div class="mx-auto max-w-4xl px-6">
            <h1 class="max-w-2xl text-4xl font-semibold tracking-tight text-ink sm:text-5xl">{{ __('Shorten links with cookieless metrics.') }}</h1>
            <p class="mt-5 max-w-xl text-lg text-muted">{{ __('Your own domain, your own numbers — no tracking anyone.') }}</p>
            <div class="mt-8 flex flex-wrap gap-3">
                <a class="nexo-btn nexo-btn--primary" href="{{ $start }}">{{ __('Shorten a link') }}</a>
                @if ($canRegister)
                    <a class="nexo-btn nexo-btn--ghost" href="{{ route('login') }}">{{ __('Sign in') }}</a>
                @endif
            </div>
        </div>
    </section>

    <section data-landing-section="producto">
        <div class="mx-auto max-w-4xl px-6">
            <h2 class="text-2xl font-semibold tracking-tight text-ink">{{ __('How it works') }}</h2>

            {{-- Kept from the landing this replaces: before any screenshot, the
                 shape of a link from THIS instance, with its real short host. --}}
            <div class="mt-6 rounded-2xl border border-line bg-surface p-5 sm:p-6">
                <p class="break-all font-mono text-sm text-muted">https://example.com/a/very/long/campaign/url?utm_source=newsletter&amp;utm_campaign=spring</p>
                <p class="mt-3 text-xl font-semibold tracking-tight text-ink sm:text-2xl">
                    <span class="text-primary">{{ $shortHost }}</span>/spring
                </p>
            </div>

            <div class="mt-10 space-y-10 sm:mt-12 sm:space-y-12">
                @foreach ($steps as $step)
                    <figure>
                        {{-- Four files per figure: theme × viewport. Both themes
                             ship because landing.css shows the one that matches
                             [data-theme]; both viewports ship because a 1280×800
                             capture shrunk to a phone is not the "legible without
                             zoom" STANDARD.md asks for. width/height are the real
                             pixels of each file, so nothing reflows on load. --}}
                        <img class="landing-shot landing-shot--desktop landing-shot--light w-full rounded-xl border border-line"
                             src="/landing/{{ $step['shot'] }}-light.webp"
                             width="1280" height="800" loading="lazy" decoding="async"
                             alt="{{ $step['caption'] }}">
                        <img class="landing-shot landing-shot--desktop landing-shot--dark w-full rounded-xl border border-line"
                             src="/landing/{{ $step['shot'] }}-dark.webp"
                             width="1280" height="800" loading="lazy" decoding="async"
                             alt="{{ $step['caption'] }}">
                        <img class="landing-shot landing-shot--mobile landing-shot--light w-full rounded-xl border border-line"
                             src="/landing/{{ $step['shot'] }}-mobile-light.webp"
                             width="390" height="844" loading="lazy" decoding="async"
                             alt="{{ $step['caption'] }}">
                        <img class="landing-shot landing-shot--mobile landing-shot--dark w-full rounded-xl border border-line"
                             src="/landing/{{ $step['shot'] }}-mobile-dark.webp"
                             width="390" height="844" loading="lazy" decoding="async"
                             alt="{{ $step['caption'] }}">
                        <figcaption class="mt-3 text-sm text-muted">{{ $step['caption'] }}</figcaption>
                    </figure>
                @endforeach
            </div>
        </div>
    </section>

    <section data-landing-section="datos">
        <div class="mx-auto max-w-4xl px-6">
            <h2 class="text-2xl font-semibold tracking-tight text-ink">{{ __('The numbers') }}</h2>
            <dl class="mt-6 border-t border-line">
                @foreach ($specs as [$term, $value])
                    <div class="flex flex-col gap-1 border-b border-line py-3 sm:flex-row sm:gap-6 sm:py-4">
                        <dt class="text-sm font-medium text-ink sm:w-56 sm:shrink-0">{{ $term }}</dt>
                        <dd class="text-sm tabular-nums text-muted">{{ $value }}</dd>
                    </div>
                @endforeach
            </dl>
        </div>
    </section>

    <section data-landing-section="preguntas">
        <div class="mx-auto max-w-4xl px-6">
            <h2 class="text-2xl font-semibold tracking-tight text-ink">{{ __('Frequent questions') }}</h2>
            <div class="mt-6 border-t border-line">
                @foreach ($faqs as $faq)
                    <details class="border-b border-line">
                        <summary class="flex min-h-11 cursor-pointer items-center text-sm font-medium text-ink">{{ $faq['q'] ?? '' }}</summary>
                        <div class="pb-4 text-sm text-muted">{!! $faq['a'] ?? '' !!}</div>
                    </details>
                @endforeach
            </div>
            <p class="mt-4">
                {{-- inline-flex + min-h-11: a thumb needs 44px, and an inline
                     link is 18 (STANDARD.md, mobile-first). --}}
                <a href="{{ route('help') }}" class="inline-flex min-h-11 items-center text-sm font-medium text-link hover:text-link-hover hover:underline">{{ __('All questions') }}</a>
            </p>
        </div>
    </section>

    <section data-landing-section="cierre">
        <div class="mx-auto max-w-4xl px-6">
            <a class="nexo-btn nexo-btn--primary" href="{{ $start }}">{{ __('Shorten a link') }}</a>
        </div>
    </section>
</x-panel-layout>
