<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Instance hosts (ADR-001)
    |--------------------------------------------------------------------------
    |
    | The short host serves redirects only (reputational fuse); the panel host
    | serves landing/auth/panel. Both belong to the instance, never hardcoded —
    | every self-hoster brings their own via env.
    |
    */

    'short_host' => env('NEXO_SHORT_HOST', 'nxo.test'),
    'panel_host' => env('NEXO_PANEL_HOST', 'nexoshort.test'),

    /*
    |--------------------------------------------------------------------------
    | Auth mode (ADR-003)
    |--------------------------------------------------------------------------
    |
    | local | sso | both. Phase 1 implements `local`. Self-hosters open/close
    | local registration; the hosted instance keeps it closed and runs SSO.
    |
    */

    'auth_mode' => env('NEXO_AUTH_MODE', 'local'),
    'allow_registration' => env('NEXO_ALLOW_REGISTRATION', true),

    /*
    |--------------------------------------------------------------------------
    | Footer attribution (add-branding-footer standard, multi-instance)
    |--------------------------------------------------------------------------
    */

    'attribution' => [
        'enabled' => env('NEXO_ATTRIBUTION_ENABLED', true),
        'text' => env('NEXO_ATTRIBUTION_TEXT', 'Powered by alvarocdev.com'),
        'url' => env('NEXO_ATTRIBUTION_URL', 'https://alvarocdev.com'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Locales (i18n en/es/pt)
    |--------------------------------------------------------------------------
    |
    | Languages offered in the switcher. `en` is the source language (strings
    | live in code via __()); es/pt are generated by scripts/generate-translations.mjs.
    |
    */

    'locales' => [
        'en' => 'English',
        'es' => 'Español',
        'pt' => 'Português',
    ],

    'repository_url' => 'https://github.com/nexo-tools/nexo-short',

];
