<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Instance hosts (ADR-001)
    |--------------------------------------------------------------------------
    |
    | The short host serves redirects only (reputational fuse); the panel host
    | serves landing/auth/panel. Both belong to the instance, never hardcoded —
    | every self-hoster brings their own via env.
    |
    */

    'short_host' => env('NEXO_SHORT_HOST', 'nxo.test'),
    'panel_host' => env('NEXO_PANEL_HOST', 'nexoshort.test'),

    /*
    |--------------------------------------------------------------------------
    | Auth mode (ADR-003)
    |--------------------------------------------------------------------------
    |
    | local | sso | both. Phase 1 implements `local`. Self-hosters open/close
    | local registration; the hosted instance keeps it closed and runs SSO.
    |
    */

    'auth_mode' => env('NEXO_AUTH_MODE', 'local'),
    'allow_registration' => env('NEXO_ALLOW_REGISTRATION', true),

    /*
    |--------------------------------------------------------------------------
    | Footer attribution (add-branding-footer standard, multi-instance)
    |--------------------------------------------------------------------------
    */

    'attribution' => [
        'enabled' => env('NEXO_ATTRIBUTION_ENABLED', true),
        'text' => env('NEXO_ATTRIBUTION_TEXT', 'Powered by alvarocdev.com'),
        'url' => env('NEXO_ATTRIBUTION_URL', 'https://alvarocdev.com'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Locales (i18n en/es/pt)
    |--------------------------------------------------------------------------
    |
    | Languages offered in the switcher. `en` is the source language (strings
    | live in code via __()); es/pt are generated by scripts/generate-translations.mjs.
    |
    */

    'locales' => [
        'en' => 'English',
        'es' => 'Español',
        'pt' => 'Português',
    ],

    'repository_url' => 'https://github.com/nexo-tools/nexo-short',

    /*
    |--------------------------------------------------------------------------
    | Slugs (ADR-005 §3/§5, SPEC Phase 1)
    |--------------------------------------------------------------------------
    |
    | Random slugs are base62 within [min, max]. Custom slugs must match
    | ^[A-Za-z0-9_-]{3,32}$ and may not collide with a reserved word.
    |
    */

    'slug' => [
        'min_length' => (int) env('NEXO_SLUG_MIN_LENGTH', 6),
        'max_length' => (int) env('NEXO_SLUG_MAX_LENGTH', 7),
    ],

    /*
    |--------------------------------------------------------------------------
    | Reserved slugs (ADR-005 §5)
    |--------------------------------------------------------------------------
    |
    | Slugs that can never be registered because they collide with system paths
    | or could impersonate the site/ecosystem. Compared case-insensitively.
    | Adapted from the nexo-links reserved-usernames pattern (CATALOG).
    |
    */

    /*
    |--------------------------------------------------------------------------
    | Anti-abuse (ADR-005)
    |--------------------------------------------------------------------------
    |
    | Creation and report rate limits, and the optional Google Safe Browsing
    | check at creation. Safe Browsing is disabled when no key is set (self-host
    | default); a flagged URL is always rejected, and on API error the behavior
    | follows `fail_closed` (default fail-open — SPEC Phase 3).
    |
    */

    'create_rate' => [
        'per_user' => (int) env('NEXO_CREATE_RATE_PER_USER', 10),
        'per_ip' => (int) env('NEXO_CREATE_RATE_PER_IP', 20),
    ],

    'report_rate' => [
        'per_ip' => (int) env('NEXO_REPORT_RATE_PER_IP', 5),
    ],

    'safe_browsing' => [
        'key' => env('NEXO_SAFE_BROWSING_KEY', ''),
        'fail_closed' => (bool) env('NEXO_SAFE_BROWSING_FAIL_CLOSED', false),
    ],

    // Reasons offered on the public report form (ADR-005 §7). Keys are stored;
    // labels are translation strings shown to the reporter.
    'report_reasons' => [
        'malicious' => 'Malicious or scam',
        'spam' => 'Spam',
        'abusive' => 'Abusive content',
        'broken' => 'Broken link',
        'other' => 'Other',
    ],

    'reserved_slugs' => [
        // System paths / ADR-005 §5 core set.
        'abuse', 'admin', 'api', 'app', 'assets', 'dashboard', 'help', 'login',
        'logout', 'panel', 'privacy', 'register', 'report', 'reports', 'robots',
        'settings', 'setup', 'status', 'storage', 'support', 'system', 'terms',
        'up', 'verify', 'www',
        // Nexo ecosystem tool names.
        'nexo', 'nexoshort', 'short', 'links', 'agenda', 'events', 'id',
    ],

];
